;********************************
; CONTROLS
;********************************
controls(
 techVersion("1.0")

 techParams(
 ;( parameter           value             )
 ;( ----------          -----             )
  ( DNW_7          	3.0 )
  ( DNW_8          	5.0 )
  ( NW_1           	0.86 )
  ( NW_2a          	0.6 )
  ( NW_2b          	1.4 )
  ( NW_3           	2.1 )
  ( NR_1           	1.0 )
  ( NR_2           	0.3 )
  ( NR_3           	0.3 )
  ( NR_4           	0.22 )
  ( NR_5           	0.4 )
  ( NR_6           	0.3 )
  ( NR_7           	1.4 )
  ( AA_1           	0.22 )
  ( AA_2           	0.22 )
  ( AA_3           	0.28 )
  ( AA_4           	0.12 )
  ( AA_5           	0.43 )
  ( AA_6           	0.43 )
  ( AA_7           	0.12 )
  ( AA_8           	0.32 )
  ( AA_9           	0.0 )
  ( AA_10          	0.42 )
  ( AA_11          	0.2 )
  ( DG_1           	0.32 )
  ( DG_2           	0.45 )
  ( DG_3           	0.32 )
  ( DG_4           	0.4 )
  ( DG_5           	0.4 )
  ( GT_1           	0.18 )
  ( GT_2           	0.18 )
  ( GT_3           	0.25 )
  ( GT_4           	0.25 )
  ( GT_5           	0.22 )
  ( GT_6           	0.32 )
  ( GT_7           	0.1 )
  ( GT_8           	0.3 )
  ( GT_9           	0.35 )
  ( GT_10a         	50.0 )
  ( GT_10b         	50.0 )
  ( GT_12          	0.14 )
  ( GT_13          	0.375 )
  ( GT_14          	0.21 )
  ( SN_1           	0.44 )
  ( SN_2           	0.44 )
  ( SN_3           	0.26 )
  ( SN_4           	0.1 )
  ( SN_5           	0.18 )
  ( SN_6           	0.32 )
  ( SN_7           	0.32 )
  ( SN_8           	0.23 )
  ( SN_9           	0.18 )
  ( SN_10          	0.02 )
  ( SN_11          	0.18 )
  ( SN_12          	0.0 )
  ( SN_13          	0.0 )
  ( SN_14          	0.38 )
  ( SN_15          	0.18 )
  ( SN_16          	0.35 )
  ( SN_17          	0.35 )
  ( SP_1           	0.44 )
  ( SP_2           	0.44 )
  ( SP_3           	0.26 )
  ( SP_4           	0.1 )
  ( SP_5           	0.18 )
  ( SP_6           	0.32 )
  ( SP_7           	0.32 )
  ( SP_8           	0.23 )
  ( SP_9           	0.18 )
  ( SP_10          	0.02 )
  ( SP_11          	0.18 )
  ( SP_12          	0.0 )
  ( SP_13          	0.0 )
  ( SP_14          	0.38 )
  ( SP_15          	0.18 )
  ( SP_16          	0.35 )
  ( SP_17          	0.35 )
  ( SAB_1          	0.43 )
  ( SAB_2          	0.43 )
  ( SAB_3          	0.22 )
  ( SAB_4          	0.22 )
  ( SAB_5          	0.45 )
  ( SAB_6          	0.22 )
  ( SAB_7          	0.22 )
  ( SAB_8          	0.22 )
  ( SAB_9          	0.3 )
  ( SAB_10         	2.0 )
  ( CT_1           	0.22 )
  ( CT_2           	0.25 )
  ( CT_3           	0.28 )
  ( CT_4           	0.2 )
  ( CT_5           	0.16 )
  ( CT_6           	0.1 )
  ( CT_7           	0.1 )
  ( CT_8           	0.12 )
  ( CT_9           	0.12 )
  ( M1_1           	0.23 )
  ( M1_2           	0.23 )
  ( M1_3           	0.005 )
  ( M1_4           	0.06 )
  ( M1_5           	0.6 )
  ( M1_6           	0.2 )
  ( M1_7           	0.3 )
  ( M1_7a          	0.75 )
  ( V1_1           	0.26 )
  ( V1_2           	0.26 )
  ( V1_3           	0.01 )
  ( V1_4           	0.06 )
  ( Mn_1           	0.28 )
  ( Mn_2           	0.28 )
  ( Mn_3           	0.01 )
  ( Mn_4           	0.06 )
  ( Mn_5           	0.6 )
  ( Mn_6           	0.2 )
  ( Mn_7           	0.3 )
  ( Mn_7a          	0.75 )
  ( Vn_1           	0.26 )
  ( Vn_2           	0.26 )
  ( Vn_3           	0.01 )
  ( Vn_4           	0.06 )
  ( V5_1           	0.36 )
  ( V5_2           	0.35 )
  ( V5_3           	0.01 )
  ( V5_4           	0.06 )
  ( MT_1           	0.44 )
  ( MT_2           	0.46 )
  ( MT_3           	0.09 )
  ( MT_4           	0.6 )
  ( MT_5           	0.56 )
  ( MT_6           	0.3 )
  ( MT_6a          	0.75 )
  ( NN_3           	0.84 )
  ( NN_4           	0.84 )
  ( NN_5           	1.0 )
  ( NN_5a          	1.8 )
  ( NN_6           	0.26 )
  ( NN_7           	0.52 )
  ( NN_8           	1.62 )
  ( MVN_4          	0.72 )
  ( MVN_5          	0.3 )
  ( MVN_5a         	0.6 )
  ( MVN_6          	0.7 )
  ( MVN_7          	0.42 )
  ( MVN_8          	0.25 )
  ( MVN_9          	0.42 )
  ( MVP_4          	0.72 )
  ( MVP_5          	0.25 )
  ( MVP_6          	0.7 )
  ( MVP_7          	0.42 )
  ( MVP_8          	0.25 )
  ( MVP_9          	0.42 )
  ( HRP_2          	0.26 )
  ( HRP_3          	0.32 )
  ( HRP_4          	0.32 )
  ( HRP_5          	0.3 )
  ( HRP_6          	0.22 )
  ( HRP_7          	1.0 )
  ( MiM_1          	4.0 )
  ( MiM_2          	1.2 )
  ( MiM_3          	0.24 )
  ( MiM_4          	0.4 )
  ( MiM_8          	35.0 )
  ( MiM_9          	0.03 )
  ( MiM_11         	0.12 )
  ( MiM_12         	0.4 )
  ( MiM_13         	2.0 )
  ( MiM_14         	4.0 )
  ( MiM_15         	0.4 )
  ( MiM_16         	0.8 )
  ( MiM_17         	0.8 )
  ( MiM_18         	2.0 )
  ( MTT_1          	1.5 )
  ( MTT_2a         	1.5 )
  ( MTT_2b         	3.0 )
  ( MTT_3          	0.3 )
  ( MTT_4          	0.42 )
  ( MTT_5          	50.0 )
  ( MTT_6          	2.25 )
  ( MTT_7          	0.3 )
  ( MTT_7b         	0.75 )
  ( MTT_9          	50.0 )
  ( MTT1_1         	1.8 )
  ( MTT1_2a        	1.8 )
  ( MTT1_2b        	3.0 )
  ( MTT1_3         	0.3 )
  ( MTT1_4         	0.42 )
  ( MTT1_5         	50.0 )
  ( MTT1_6         	3.24 )
  ( MTT1_7         	0.3 )
  ( MTT1_7b        	0.75 )
  ( MTT1_9         	50.0 )
  ( MTT2_1         	2.6 )
  ( MTT2_2a        	2.5 )
  ( MTT2_2b        	4.0 )
  ( MTT2_3         	0.4 )
  ( MTT2_4         	0.45 )
  ( MTT2_5         	50.0 )
  ( MTT2_6         	6.76 )
  ( MTT2_7         	0.3 )
  ( MTT2_7b        	0.75 )
  ( MTT2_9         	50.0 )
  ( RS_M1          	0.068 )
  ( RS_M2          	0.08986 )
  ( RS_M3          	0.08986 )
  ( RS_M4          	0.08986 )
  ( RS_M5          	0.08986 )
  ( RS_M6          	0.0083 )
  ( TK_GT          	2e-07 )
  ( TK_M1          	5.5e-07 )
  ( TK_M2          	5.5e-07 )
  ( TK_M3          	5.5e-07 )
  ( TK_M4          	5.5e-07 )
  ( TK_M5          	5.5e-07 )
  ( TK_M6          	4.065e-06 )
 ) ;techParams

 viewTypeUnits(
 ;( viewType            userUnit       dbuperuu           )
 ;( --------            --------       --------           )
  ( maskLayout     	"micron"       	1000            )
  ( schematic      	"inch"         	160             )
  ( schematicSymbol	"inch"         	160             )
  ( netlist        	"inch"         	160             )
  ( hierDesign     	"micron"       	1000            )
 ) ;viewTypeUnits

 mfgGridResolution(
      ( 0.001000 )
 ) ;mfgGridResolution

) ;controls


;********************************
; LAYER DEFINITION
;********************************
layerDefinitions(

 techPurposes(
 ;( PurposeName               Purpose#   Abbreviation )
 ;( -----------               --------   ------------ )
 ;User-Defined Purposes:
  ( metal1                    1          m1           )
  ( metal2                    2          m2           )
  ( metal3                    3          m3           )
  ( metal4                    4          m4           )
  ( metal5                    5          m5           )
  ( metal6                    6          m6           )
  ( topmetal1                 7          tm1          )
  ( topmetal2                 8          tm2          )
  ( ldbk12                    9          l12          )
  ( ldbkn                     10         ln           )
  ( ldbkp                     11         lp           )
  ( ldbk24                    12         l24          )
  ( ttxt                      13         ttx          )
  ( btxt                      14         btx          )
  ( ctxt                      15         ctx          )
  ( subtxt                    16         sub          )
  ( weltxt                    17         wel          )
  ( diftxt                    18         dif          )
  ( polytxt                   19         ply          )
  ( opcba                     20         oba          )
  ( opcbm                     21         obm          )
  ( opcbp                     22         obp          )
  ( slot                      23         slo          )
  ( gtfuse                    24         gtf          )
  ( efuse                     25         efu          )
  ( mk1                       26         mk1          )
  ( indr                      27         res          )
  ( indor                     28         dor          )
  ( tem                       29         tem          )
  ( luwmk1                    30         lmk1         )
  ( vddmk1                    31         vdmk1        )
  ( vssmk1                    32         vsmk1        )
 ;System-Reserved Purposes:
  ( warning                   234        wng          )
  ( tool1                     235        tl1          )
  ( tool0                     236        tl0          )
  ( label                     237        lbl          )
  ( flight                    238        flt          )
  ( error                     239        err          )
  ( annotate                  240        ant          )
  ( drawing1                  241        dr1          )
  ( drawing2                  242        dr2          )
  ( drawing3                  243        dr3          )
  ( drawing4                  244        dr4          )
  ( drawing5                  245        dr5          )
  ( drawing6                  246        dr6          )
  ( drawing7                  247        dr7          )
  ( drawing8                  248        dr8          )
  ( drawing9                  249        dr9          )
  ( boundary                  250        bnd          )
  ( pin                       251        pin          )
  ( drawing                   252        drw          )
  ( net                       253        net          )
  ( cell                      254        cel          )
  ( all                       255        all          )
 ) ;techPurposes

 techLayers(
 ;( LayerName                 Layer#     Abbreviation )
 ;( ---------                 ------     ------------ )
 ;User-Defined Layers:
  ( DUMAA                     0          DUMAA        )
  ( SURNW                     1          SURNW        )
  ( STIDMY                    2          STIDMY       )
  ( SDOP                      3          SDOP         )
  ( NEGR                      4          NEGR         )
  ( RFDN5T                    5          RFDN5T       )
  ( RFDN6T                    6          RFDN6T       )
  ( AMO                       7          AMO          )
  ( CO                        8          CO           )
  ( KV                        9          KV           )
  ( AA                        10         AA           )
  ( AR                        11         AR           )
  ( NPAA                      12         NPAA         )
  ( PPAA                      13         PPAA         )
  ( NW                        14         NW           )
  ( TP                        15         TP           )
  ( PC                        16         PC           )
  ( DP                        17         DP           )
  ( CL                        18         CL           )
  ( DNW                       19         DNW          )
  ( PW                        20         PW           )
  ( NC                        21         NC           )
  ( CPT                       22         CPT          )
  ( BNP                       23         BNP          )
  ( TN                        24         TN           )
  ( CODE                      25         CODE         )
  ( LOGO                      26         LOGO         )
  ( ONO                       27         ONO          )
  ( BC                        28         BC           )
  ( DG                        29         DG           )
  ( GT                        30         GT           )
  ( P2                        31         P2           )
  ( VMK1                      32         VMK1         )
  ( MIMSHD                    33         MIMSHD       )
  ( HR                        34         HR           )
  ( NLL                       35         NLL          )
  ( NLH                       36         NLH          )
  ( PLH                       37         PLH          )
  ( PLL                       38         PLL          )
  ( HRP                       39         HRP          )
  ( SN                        40         SN           )
  ( ESD1                      41         ESD1         )
  ( ESD2                      42         ESD2         )
  ( SP                        43         SP           )
  ( MVP                       44         MVP          )
  ( MVN                       45         MVN          )
  ( VTPH                      46         VTPH         )
  ( VTNH                      47         VTNH         )
  ( SAB                       48         SAB          )
  ( IDT                       49         IDT          )
  ( CT                        50         CT           )
  ( CM                        51         CM           )
  ( M1DUM                     52         M1DUM        )
  ( DDN                       53         DDN          )
  ( HVBN                      54         HVBN         )
  ( NDDD                      55         NDDD         )
  ( DDP                       56         DDP          )
  ( MOMDMY                    57         MOMDMY       )
  ( MIM                       58         MIM          )
  ( M0                        59         M0           )
  ( INST                      60         INST         )
  ( M1                        61         M1           )
  ( M2                        62         M2           )
  ( M3                        63         M3           )
  ( M4                        64         M4           )
  ( M5                        65         M5           )
  ( M6                        66         M6           )
  ( M2DUM                     67         M2DUM        )
  ( MTT1                      68         MTT1         )
  ( PFL                       69         PFL          )
  ( V1                        70         V1           )
  ( V2                        71         V2           )
  ( V3                        72         V3           )
  ( V4                        73         V4           )
  ( V5                        74         V5           )
  ( M3DUM                     75         M3DUM        )
  ( SUBDMY                    76         SUBDMY       )
  ( NDRF                      77         NDRF         )
  ( M4DUM                     78         M4DUM        )
  ( PIPR                      79         PIPR         )
  ( PA                        80         PA           )
  ( FUSE                      81         FUSE         )
  ( PI                        82         PI           )
  ( ALPA                      83         ALPA         )
  ( MTT2                      84         MTT2         )
  ( PSUB                      85         PSUB         )
  ( VSIA                      86         VSIA         )
  ( TXT                       87         TXT          )
  ( WN                        88         WN           )
  ( WP                        89         WP           )
  ( DUMBM                     90         DUMBM        )
  ( DUMBA                     91         DUMBA        )
  ( DUMBP                     92         DUMBP        )
  ( VARMOS                    93         VARMOS       )
  ( VARJUN                    94         VARJUN       )
  ( RESNW                     95         RESNW        )
  ( RESP1                     96         RESP1        )
  ( RESAA                     97         RESAA        )
  ( SUBD                      98         SUBD         )
  ( PDRF                      99         PDRF         )
  ( OPC                       100        OPC          )
  ( MIMCKT                    101        MIMCKT       )
  ( MARKS                     102        MARKS        )
  ( M3DUB                     103        M3DUB        )
  ( M4DUB                     104        M4DUB        )
  ( PWH                       105        PWH          )
  ( NWH                       106        NWH          )
  ( PPCI                      107        PPCI         )
  ( NPCI                      108        NPCI         )
  ( M5DUB                     109        M5DUB        )
  ( M6DUB                     110        M6DUB        )
  ( RF3T                      111        RF3T         )
  ( MARKF                     112        MARKF        )
  ( PIP                       113        PIP          )
  ( NLHT                      114        NLHT         )
  ( PLHT                      115        PLHT         )
  ( LV                        116        LV           )
  ( PWHT                      117        PWHT         )
  ( NFDMK                     118        NFDMK        )
  ( NWHT                      119        NWHT         )
  ( TM1                       120        TM1          )
  ( TV1                       121        TV1          )
  ( TM2                       122        TM2          )
  ( TV2                       123        TV2          )
  ( ESD5V                     124        ESD5V        )
  ( TG                        125        TG           )
  ( DUPMK1                    126        DUPMK1       )
  ( BORDER                    127        BORDER       )
  ( M5DUM                     128        M5DUM        )
  ( TM1DUM                    129        TM1DUM       )
  ( TM1TXT                    130        TM1TXT       )
  ( HTNWL                     131        HTNWL        )
  ( EXCLU                     132        EXCLU        )
  ( ESDIO1                    133        ESDIO1       )
  ( DMPNP                     134        DMPNP        )
  ( PDC                       135        PDC          )
;(                        136                  )
  ( CAPBP                     137        CAPBP        )
  ( DSTR                      138        DSTR         )
  ( DCTY                      139        DCTY         )
;(                        140                  )
  ( M1TXT                     141        M1TXT        )
  ( M2TXT                     142        M2TXT        )
  ( M3TXT                     143        M3TXT        )
  ( M4TXT                     144        M4TXT        )
  ( M5TXT                     145        M5TXT        )
  ( M6TXT                     146        M6TXT        )
  ( LVP                       147        LVP          )
  ( LVN                       148        LVN          )
  ( "0M"                      149        "0M"         )
  ( MARKG                     150        MARKG        )
  ( M1B                       151        M1B          )
  ( M2B                       152        M2B          )
  ( M3B                       153        M3B          )
  ( M4B                       154        M4B          )
  ( M5B                       155        M5B          )
  ( M6B                       156        M6B          )
  ( MnSLOTB                   157        MnSLOTB      )
  ( HVDMY                     158        HVDMY        )
  ( RGM                       159        RGM          )
  ( MOSCKT                    160        MOSCKT       )
  ( LDBK12                    161        LDBK12       )
  ( LDBK24                    162        LDBK24       )
  ( LDBKN                     163        LDBKN        )
  ( LDBKP                     164        LDBKP        )
  ( HT                        165        HT           )
  ( TM2DUM                    166        TM2DUM       )
  ( DUMGT                     167        DUMGT        )
;(                      168                )
  ( M6DUM                     169        M6DUM        )
  ( DNWTR                     170        DNWTR        )
  ( M1R                       171        M1R          )
  ( M2R                       172        M2R          )
  ( M3R                       173        M3R          )
  ( M4R                       174        M4R          )
  ( M5R                       175        M5R          )
  ( M6R                       176        M6R          )
  ( RESCKT                    177        RESCKT       )
  ( MFUSE                     178        MFUSE        )
  ( POWRING                   179        POWRING      )
  ( NODMF                     180        NODMF        )
  ( HRPDMY                    181        HRPDMY       )
  ( RESP3T                    182        RESP3T       )
  ( M1DUB                     183        M1DUB        )
  ( M2DUB                     184        M2DUB        )
  ( TM2TXT                    185        TM2TXT       )
  ( TM1R                      186        TM1R         )
  ( TM2R                      187        TM2R         )
  ( DDNW                      188        DDNW         )
  ( MIMDMY                    189        MIMDMY       )
  ( INDMY                     190        INDMY        )
  ( RFDEV                     191        RFDEV        )
  ( RFMOSD                    192        RFMOSD       )
  ( JVARDUM                   193        JVARDUM      )
  ( ESDIO2                    194        ESDIO2       )
 ;System-Reserved Layers:
  ( Unrouted                  200        Unroute      )
  ( Row                       201        Row          )
  ( Group                     202        Group        )
  ( Cannotoccupy              203        noOcupy      )
  ( Canplace                  204        Canplac      )
  ( hardFence                 205        hardFnc      )
  ( softFence                 206        softFnc      )
  ( y0                        207        y0           )
  ( y1                        208        y1           )
  ( y2                        209        y2           )
  ( y3                        210        y3           )
  ( y4                        211        y4           )
  ( y5                        212        y5           )
  ( y6                        213        y6           )
  ( y7                        214        y7           )
  ( y8                        215        y8           )
  ( y9                        216        y9           )
  ( designFlow                217        dsnFlow      )
  ( stretch                   218        stretch      )
  ( edgeLayer                 219        edgeLyr      )
  ( changedLayer              220        chngLyr      )
  ( unset                     221        unset        )
  ( unknown                   222        unknown      )
  ( spike                     223        spike        )
  ( hiz                       224        hiz          )
  ( resist                    225        resist       )
  ( drive                     226        drive        )
  ( supply                    227        supply       )
  ( wire                      228        wire         )
  ( pin                       229        pin          )
  ( text                      230        text         )
  ( device                    231        device       )
  ( border                    232        border       )
  ( snap                      233        snap         )
  ( align                     234        align        )
  ( prBoundary                235        prBndry      )
  ( instance                  236        instnce      )
  ( annotate                  237        anotate      )
  ( marker                    238        marker       )
  ( select                    239        select       )
  ( grid                      251        grid         )
  ( axis                      252        axis         )
  ( hilite                    253        hilite       )
  ( background                254        bkground     )
 ) ;techLayers

 techLayerPurposePriorities(
 ;layers are ordered from lowest to highest priority
 ;( LayerName                 Purpose    )
 ;( ---------                 -------    )
  ( background                drawing    )
  ( grid                      drawing    )
  ( grid                      drawing1   )
  ( annotate                  drawing    )
  ( annotate                  drawing1   )
  ( annotate                  drawing2   )
  ( annotate                  drawing3   )
  ( annotate                  drawing4   )
  ( annotate                  drawing5   )
  ( annotate                  drawing6   )
  ( annotate                  drawing7   )
  ( annotate                  drawing8   )
  ( annotate                  drawing9   )
  ( instance                  drawing    )
  ( instance                  label      )
  ( prBoundary                drawing    )
  ( prBoundary                boundary   )
  ( prBoundary                label      )
  ( align                     drawing    )
  ( hardFence                 drawing    )
  ( softFence                 drawing    )
  ( text                      drawing    )
  ( text                      drawing1   )
  ( text                      drawing2   )
  ( border                    drawing    )
  ( device                    drawing    )
  ( device                    label      )
  ( device                    drawing1   )
  ( device                    drawing2   )
  ( device                    annotate   )
  ( wire                      drawing    )
  ( wire                      label      )
  ( wire                      flight     )
  ( pin                       label      )
  ( pin                       drawing    )
  ( pin                       annotate   )
  ( axis                      drawing    )
  ( edgeLayer                 drawing    )
  ( edgeLayer                 pin        )
  ( snap                      drawing    )
  ( stretch                   drawing    )
  ( y0                        drawing    )
  ( y1                        drawing    )
  ( y2                        drawing    )
  ( y3                        drawing    )
  ( y4                        drawing    )
  ( y5                        drawing    )
  ( y6                        drawing    )
  ( y7                        drawing    )
  ( y8                        drawing    )
  ( y9                        drawing    )
  ( hilite                    drawing    )
  ( hilite                    drawing1   )
  ( hilite                    drawing2   )
  ( hilite                    drawing3   )
  ( hilite                    drawing4   )
  ( hilite                    drawing5   )
  ( hilite                    drawing6   )
  ( hilite                    drawing7   )
  ( hilite                    drawing8   )
  ( hilite                    drawing9   )
  ( select                    drawing    )
  ( drive                     drawing    )
  ( hiz                       drawing    )
  ( resist                    drawing    )
  ( spike                     drawing    )
  ( supply                    drawing    )
  ( unknown                   drawing    )
  ( unset                     drawing    )
  ( designFlow                drawing    )
  ( designFlow                drawing1   )
  ( designFlow                drawing2   )
  ( designFlow                drawing3   )
  ( designFlow                drawing4   )
  ( designFlow                drawing5   )
  ( designFlow                drawing6   )
  ( designFlow                drawing7   )
  ( designFlow                drawing8   )
  ( designFlow                drawing9   )
  ( changedLayer              tool0      )
  ( changedLayer              tool1      )
  ( marker                    warning    )
  ( marker                    error      )
  ( Row                       drawing    )
  ( Row                       label      )
  ( Group                     drawing    )
  ( Group                     label      )
  ( Cannotoccupy              drawing    )
  ( Cannotoccupy              boundary   )
  ( Canplace                  drawing    )
  ( Unrouted                  drawing    )
  ( Unrouted                  drawing1   )
  ( Unrouted                  drawing2   )
  ( Unrouted                  drawing3   )
  ( Unrouted                  drawing4   )
  ( Unrouted                  drawing5   )
  ( Unrouted                  drawing6   )
  ( Unrouted                  drawing7   )
  ( Unrouted                  drawing8   )
  ( Unrouted                  drawing9   )
  ( "0M"                      drawing    )
  ( RGM                       drawing    )
  ( HT                        drawing    )
  ( NEGR                      drawing    )
  ( AA                        drawing    )
  ( DUMAA                     drawing    )
  ( NPAA                      drawing    )
  ( PPAA                      drawing    )
  ( NW                        drawing    )
  ( GT                        drawing    )
  ( DUMGT                     drawing    )
  ( DG                        drawing    )
  ( HRP                       drawing    )
  ( SN                        drawing    )
  ( SP                        drawing    )
  ( SAB                       drawing    )
  ( VSIA                      drawing    )
  ( CT                        drawing    )
  ( M1                        drawing    )
  ( M2                        drawing    )
  ( M3                        drawing    )
  ( M4                        drawing    )
  ( M5                        drawing    )
  ( M6                        drawing    )
  ( V1                        drawing    )
  ( V2                        drawing    )
  ( V3                        drawing    )
  ( V4                        drawing    )
  ( V5                        drawing    )
  ( PA                        drawing    )
  ( M1TXT                     drawing    )
  ( M2TXT                     drawing    )
  ( M3TXT                     drawing    )
  ( M4TXT                     drawing    )
  ( M5TXT                     drawing    )
  ( M6TXT                     drawing    )
  ( PSUB                      drawing    )
  ( RESNW                     drawing    )
  ( RESP1                     drawing    )
  ( RESP3T                    drawing    )
  ( RESAA                     drawing    )
  ( SUBD                      drawing    )
  ( HTNWL                     drawing    )
  ( EXCLU                     drawing    )
  ( ESDIO1                    drawing    )
  ( POWRING                   drawing    )
  ( ESDIO2                    drawing    )
  ( DMPNP                     drawing    )
  ( CAPBP                     drawing    )
  ( DSTR                      drawing    )
  ( SURNW                     drawing    )
  ( AMO                       drawing    )
  ( CO                        drawing    )
  ( BORDER                    drawing    )
  ( KV                        drawing    )
  ( AR                        drawing    )
  ( TP                        drawing    )
  ( PC                        drawing    )
  ( DP                        drawing    )
  ( CL                        drawing    )
  ( DNW                       drawing    )
  ( PW                        drawing    )
  ( NC                        drawing    )
  ( CPT                       drawing    )
  ( BNP                       drawing    )
  ( TN                        drawing    )
  ( CODE                      drawing    )
  ( LOGO                      drawing    )
  ( ONO                       drawing    )
  ( BC                        drawing    )
  ( P2                        drawing    )
  ( HR                        drawing    )
  ( NLL                       drawing    )
  ( NLH                       drawing    )
  ( PLH                       drawing    )
  ( PLL                       drawing    )
  ( ESD1                      drawing    )
  ( ESD2                      drawing    )
  ( MVP                       drawing    )
  ( MVN                       drawing    )
  ( VTPH                      drawing    )
  ( VTNH                      drawing    )
  ( IDT                       drawing    )
  ( CM                        drawing    )
  ( DDN                       drawing    )
  ( HVBN                      drawing    )
  ( NDDD                      drawing    )
  ( DDP                       drawing    )
  ( MIM                       drawing    )
  ( M0                        drawing    )
  ( INST                      drawing    )
  ( M1DUM                     drawing    )
  ( M2DUM                     drawing    )
  ( M3DUM                     drawing    )
  ( M4DUM                     drawing    )
  ( M5DUM                     drawing    )
  ( M6DUM                     drawing    )
  ( PIPR                      drawing    )
  ( FUSE                      drawing    )
  ( PI                        drawing    )
  ( ALPA                      drawing    )
  ( LDBK12                    drawing    )
  ( LDBK24                    drawing    )
  ( LDBKN                     drawing    )
  ( LDBKP                     drawing    )
  ( TXT                       ttxt       )
  ( TXT                       btxt       )
  ( TXT                       ctxt       )
  ( WN                        drawing    )
  ( WP                        drawing    )
  ( DUMBM                     drawing    )
  ( DUMBA                     drawing    )
  ( DUMBP                     drawing    )
  ( VARMOS                    drawing    )
  ( VARJUN                    drawing    )
  ( PFL                       drawing    )
  ( SDOP                      drawing    )
  ( OPC                       opcba      )
  ( OPC                       opcbp      )
  ( OPC                       opcbm      )
  ( NDRF                      drawing    )
  ( PDRF                      drawing    )
  ( PPCI                      drawing    )
  ( NPCI                      drawing    )
  ( PWHT                      drawing    )
  ( NWHT                      drawing    )
  ( PIP                       drawing    )
  ( NLHT                      drawing    )
  ( PLHT                      drawing    )
  ( TM1                       drawing    )
  ( TM1DUM                    drawing    )
  ( TM1TXT                    drawing    )
  ( TV1                       drawing    )
  ( TM2                       drawing    )
  ( TM2DUM                    drawing    )
  ( TM2TXT                    drawing    )
  ( TV2                       drawing    )
  ( ESD5V                     drawing    )
  ( LV                        drawing    )
  ( TG                        drawing    )
  ( PDC                       drawing    )
  ( DCTY                      drawing    )
  ( TXT                       subtxt     )
  ( TXT                       weltxt     )
  ( TXT                       diftxt     )
  ( TXT                       polytxt    )
  ( M1B                       drawing    )
  ( M2B                       drawing    )
  ( M3B                       drawing    )
  ( M4B                       drawing    )
  ( M5B                       drawing    )
  ( M6B                       drawing    )
  ( M1DUB                     drawing    )
  ( M2DUB                     drawing    )
  ( M3DUB                     drawing    )
  ( M4DUB                     drawing    )
  ( M5DUB                     drawing    )
  ( M6DUB                     drawing    )
  ( PWH                       drawing    )
  ( NWH                       drawing    )
  ( M1R                       drawing    )
  ( M2R                       drawing    )
  ( M3R                       drawing    )
  ( M4R                       drawing    )
  ( M5R                       drawing    )
  ( M6R                       drawing    )
  ( MnSLOTB                   metal1     )
  ( MnSLOTB                   metal2     )
  ( MnSLOTB                   metal3     )
  ( MnSLOTB                   metal4     )
  ( MnSLOTB                   metal5     )
  ( MnSLOTB                   metal6     )
  ( NODMF                     drawing    )
  ( RFDEV                     drawing    )
  ( RFMOSD                    drawing    )
  ( TM1R                      drawing    )
  ( TM2R                      drawing    )
  ( JVARDUM                   drawing    )
  ( HRPDMY                    drawing    )
  ( MIMDMY                    drawing    )
  ( INDMY                     drawing    )
  ( STIDMY                    drawing    )
  ( SUBDMY                    drawing    )
  ( DDNW                      drawing    )
  ( LVP                       drawing    )
  ( LVN                       drawing    )
  ( HVDMY                     drawing    )
  ( MOSCKT                    drawing    )
  ( DNWTR                     drawing    )
  ( RESCKT                    drawing    )
  ( NFDMK                     drawing    )
  ( MOMDMY                    drawing    )
  ( MOMDMY                    tem        )
  ( RF3T                      drawing    )
  ( MFUSE                     drawing    )
  ( MARKG                     drawing    )
  ( MARKF                     drawing    )
  ( MIMCKT                    drawing    )
  ( M1                        slot       )
  ( M2                        slot       )
  ( M3                        slot       )
  ( M4                        slot       )
  ( M5                        slot       )
  ( M6                        slot       )
  ( FUSE                      gtfuse     )
  ( FUSE                      efuse      )
  ( FUSE                      mk1        )
  ( MARKS                     drawing    )
  ( DUPMK1                    drawing    )
  ( INDMY                     indr       )
  ( INDMY                     indor      )
  ( MTT1                      drawing    )
  ( MTT2                      drawing    )
  ( RFDN5T                    drawing    )
  ( RFDN6T                    drawing    )
  ( MIMSHD                    drawing    )
  ( VMK1                      luwmk1     )
  ( VMK1                      vddmk1     )
  ( VMK1                      vssmk1     )
  ( snap                      boundary   )
 ) ;techLayerPurposePriorities

 techDisplays(
 ;( LayerName    Purpose      Packet          Vis Sel Con2ChgLy DrgEnbl Valid )
 ;( ---------    -------      ------          --- --- --------- ------- ----- )
  ( background   drawing      background       t nil t nil nil )
  ( grid         drawing      grid             t nil t nil nil )
  ( grid         drawing1     grid1            t nil t nil nil )
  ( annotate     drawing      annotate         t t t t nil )
  ( annotate     drawing1     annotate1        t t t t nil )
  ( annotate     drawing2     annotate2        t t t t nil )
  ( annotate     drawing3     annotate3        t t t t nil )
  ( annotate     drawing4     annotate4        t t t t nil )
  ( annotate     drawing5     annotate5        t t t t nil )
  ( annotate     drawing6     annotate6        t t t t nil )
  ( annotate     drawing7     annotate7        t t t t nil )
  ( annotate     drawing8     annotate8        t t t t nil )
  ( annotate     drawing9     annotate9        t t t t nil )
  ( instance     drawing      instance         t t t t nil )
  ( instance     label        instanceLbl      t t t t nil )
  ( prBoundary   drawing      prBoundary       t t t t nil )
  ( prBoundary   boundary     prBoundaryBnd    t t t t nil )
  ( prBoundary   label        prBoundaryLbl    t t t t nil )
  ( align        drawing      defaultPacket    t t t t nil )
  ( hardFence    drawing      hardFence        t t t t nil )
  ( softFence    drawing      softFence        t t t t nil )
  ( text         drawing      text             t t t t nil )
  ( text         drawing1     text1            t t t t nil )
  ( text         drawing2     text2            t t t t nil )
  ( border       drawing      border           t t t t nil )
  ( device       drawing      device           t t t t nil )
  ( device       label        deviceLbl        t t t t nil )
  ( device       drawing1     device1          t t t t nil )
  ( device       drawing2     device2          t t t t nil )
  ( device       annotate     deviceAnt        t t t t nil )
  ( wire         drawing      wire             t t t t nil )
  ( wire         label        wireLbl          t t t t nil )
  ( wire         flight       wireFlt          t t t t nil )
  ( pin          label        pinLbl           t t t t nil )
  ( pin          drawing      pin              t t t t nil )
  ( pin          annotate     pinAnt           t t t t nil )
  ( axis         drawing      axis             t nil t t nil )
  ( edgeLayer    drawing      edgeLayer        t t t t nil )
  ( edgeLayer    pin          edgeLayerPin     t t t t nil )
  ( snap         drawing      snap             t t t t nil )
  ( stretch      drawing      stretch          t t t t nil )
  ( y0           drawing      y0               t t t t nil )
  ( y1           drawing      y1               t t t t nil )
  ( y2           drawing      y2               t t t t nil )
  ( y3           drawing      y3               t t t t nil )
  ( y4           drawing      y4               t t t t nil )
  ( y5           drawing      y5               t t t t nil )
  ( y6           drawing      y6               t t t t nil )
  ( y7           drawing      y7               t t t t nil )
  ( y8           drawing      y8               t t t t nil )
  ( y9           drawing      y9               t t t t nil )
  ( hilite       drawing      hilite           t t t t nil )
  ( hilite       drawing1     hilite1          t t t t nil )
  ( hilite       drawing2     hilite2          t t t t nil )
  ( hilite       drawing3     hilite3          t t t t nil )
  ( hilite       drawing4     hilite4          t t t t nil )
  ( hilite       drawing5     hilite5          t t t t nil )
  ( hilite       drawing6     hilite6          t t t t nil )
  ( hilite       drawing7     hilite7          t t t t nil )
  ( hilite       drawing8     hilite8          t t t t nil )
  ( hilite       drawing9     hilite9          t t t t nil )
  ( select       drawing      select           t t t t nil )
  ( drive        drawing      drive            t t t t nil )
  ( hiz          drawing      hiz              t t t t nil )
  ( resist       drawing      resist           t t t t nil )
  ( spike        drawing      spike            t t t t nil )
  ( supply       drawing      supply           t t t t nil )
  ( unknown      drawing      unknown          t t t t nil )
  ( unset        drawing      unset            t t t t nil )
  ( designFlow   drawing      designFlow       t nil nil nil nil )
  ( designFlow   drawing1     designFlow1      t nil nil nil nil )
  ( designFlow   drawing2     designFlow2      t nil nil nil nil )
  ( designFlow   drawing3     designFlow3      t nil nil nil nil )
  ( designFlow   drawing4     designFlow4      t nil nil nil nil )
  ( designFlow   drawing5     designFlow5      t nil nil nil nil )
  ( designFlow   drawing6     designFlow6      t nil nil nil nil )
  ( designFlow   drawing7     designFlow7      t nil nil nil nil )
  ( designFlow   drawing8     designFlow8      t nil nil nil nil )
  ( designFlow   drawing9     designFlow9      t nil nil nil nil )
  ( changedLayer tool0        changedLayerTl0  nil nil t nil nil )
  ( changedLayer tool1        changedLayerTl1  nil nil t nil nil )
  ( marker       warning      markerWarn       t t t t nil )
  ( marker       error        markerErr        t t t t nil )
  ( Row          drawing      Row              t t t t nil )
  ( Row          label        RowLbl           t t t t nil )
  ( Group        drawing      Group            t t t t nil )
  ( Group        label        GroupLbl         t t t t nil )
  ( Cannotoccupy drawing      Cannotoccupy     t t t t nil )
  ( Cannotoccupy boundary     CannotoccupyBnd  t t t t nil )
  ( Canplace     drawing      Canplace         t t t t nil )
  ( Unrouted     drawing      Unrouted         t t t t nil )
  ( Unrouted     drawing1     Unrouted1        t t t t nil )
  ( Unrouted     drawing2     Unrouted2        t t t t nil )
  ( Unrouted     drawing3     Unrouted3        t t t t nil )
  ( Unrouted     drawing4     Unrouted4        t t t t nil )
  ( Unrouted     drawing5     Unrouted5        t t t t nil )
  ( Unrouted     drawing6     Unrouted6        t t t t nil )
  ( Unrouted     drawing7     Unrouted7        t t t t nil )
  ( Unrouted     drawing8     Unrouted8        t t t t nil )
  ( Unrouted     drawing9     Unrouted9        t t t t nil )
  ( "0M"         drawing      "0m"             t t t t t )
  ( RGM          drawing      rgm              t t t t t )
  ( HT           drawing      ht               t t t t t )
  ( NEGR         drawing      negr             t t t t t )
  ( AA           drawing      aa               t t t t t )
  ( DUMAA        drawing      dumaa            t t t t t )
  ( NPAA         drawing      npaa             t t t t t )
  ( PPAA         drawing      ppaa             t t t t t )
  ( NW           drawing      nw               t t t t t )
  ( GT           drawing      gt               t t t t t )
  ( DUMGT        drawing      dumgt            t t t t t )
  ( DG           drawing      dg               t t t t t )
  ( HRP          drawing      hrp              t t t t t )
  ( SN           drawing      sn               t t t t t )
  ( SP           drawing      sp               t t t t t )
  ( SAB          drawing      sab              t t t t t )
  ( VSIA         drawing      vsia             t t t t t )
  ( CT           drawing      ct               t t t t t )
  ( M1           drawing      m1               t t t t t )
  ( M2           drawing      m2               t t t t t )
  ( M3           drawing      m3               t t t t t )
  ( M4           drawing      m4               t t t t t )
  ( M5           drawing      m5               t t t t t )
  ( M6           drawing      m6               t t t t t )
  ( V1           drawing      v1               t t t t t )
  ( V2           drawing      v2               t t t t t )
  ( V3           drawing      v3               t t t t t )
  ( V4           drawing      v4               t t t t t )
  ( V5           drawing      v5               t t t t t )
  ( PA           drawing      pa               t t t t t )
  ( M1TXT        drawing      m1txt            t t t t t )
  ( M2TXT        drawing      m2txt            t t t t t )
  ( M3TXT        drawing      m3txt            t t t t t )
  ( M4TXT        drawing      m4txt            t t t t t )
  ( M5TXT        drawing      m5txt            t t t t t )
  ( M6TXT        drawing      m6txt            t t t t t )
  ( PSUB         drawing      psub             t t t t t )
  ( RESNW        drawing      resnw            t t t t t )
  ( RESP1        drawing      resp1            t t t t t )
  ( RESP3T       drawing      resp3t           t t t t t )
  ( RESAA        drawing      resaa            t t t t t )
  ( SUBD         drawing      subd             t t t t t )
  ( HTNWL        drawing      htnwl            t t t t t )
  ( EXCLU        drawing      exclu            t t t t t )
  ( ESDIO1       drawing      esdio1           t t t t t )
  ( POWRING      drawing      powring          t t t t t )
  ( ESDIO2       drawing      esdio2           t t t t t )
  ( DMPNP        drawing      dmpnp            t t t t t )
  ( CAPBP        drawing      capbp            t t t t t )
  ( DSTR         drawing      dstr             t t t t t )
  ( SURNW        drawing      surnw            t t t t t )
  ( AMO          drawing      amo              t t t t t )
  ( CO           drawing      co               t t t t t )
  ( BORDER       drawing      border           t t t t t )
  ( KV           drawing      kv               t t t t t )
  ( AR           drawing      ar               t t t t t )
  ( TP           drawing      tp               t t t t t )
  ( PC           drawing      pc               t t t t t )
  ( DP           drawing      dp               t t t t t )
  ( CL           drawing      cl               t t t t t )
  ( DNW          drawing      dnw              t t t t t )
  ( PW           drawing      pw               t t t t t )
  ( NC           drawing      nc               t t t t t )
  ( CPT          drawing      cpt              t t t t t )
  ( BNP          drawing      bnp              t t t t t )
  ( TN           drawing      tn               t t t t t )
  ( CODE         drawing      code             t t t t t )
  ( LOGO         drawing      logo             t t t t t )
  ( ONO          drawing      ono              t t t t t )
  ( BC           drawing      bc               t t t t t )
  ( P2           drawing      p2               t t t t t )
  ( HR           drawing      hr               t t t t t )
  ( NLL          drawing      nll              t t t t t )
  ( NLH          drawing      nlh              t t t t t )
  ( PLH          drawing      plh              t t t t t )
  ( PLL          drawing      pll              t t t t t )
  ( ESD1         drawing      esd1             t t t t t )
  ( ESD2         drawing      esd2             t t t t t )
  ( MVP          drawing      mvp              t t t t t )
  ( MVN          drawing      mvn              t t t t t )
  ( VTPH         drawing      vtph             t t t t t )
  ( VTNH         drawing      vtnh             t t t t t )
  ( IDT          drawing      idt              t t t t t )
  ( CM           drawing      cm               t t t t t )
  ( DDN          drawing      ddn              t t t t t )
  ( HVBN         drawing      hvbn             t t t t t )
  ( NDDD         drawing      nddd             t t t t t )
  ( DDP          drawing      ddp              t t t t t )
  ( MIM          drawing      mim              t t t t t )
  ( M0           drawing      m0               t t t t t )
  ( INST         drawing      inst             t t t t t )
  ( M1DUM        drawing      m1dum            t t t t t )
  ( M2DUM        drawing      m2dum            t t t t t )
  ( M3DUM        drawing      m3dum            t t t t t )
  ( M4DUM        drawing      m4dum            t t t t t )
  ( M5DUM        drawing      m5dum            t t t t t )
  ( M6DUM        drawing      m6dum            t t t t t )
  ( PIPR         drawing      pipr             t t t t t )
  ( FUSE         drawing      fuse             t t t t t )
  ( PI           drawing      pi               t t t t t )
  ( ALPA         drawing      alpa             t t t t t )
  ( LDBK12       drawing      ldbk12           t t t t t )
  ( LDBK24       drawing      ldbk24           t t t t t )
  ( LDBKN        drawing      ldbkn            t t t t t )
  ( LDBKP        drawing      ldbkp            t t t t t )
  ( TXT          ttxt         ttxt             t t t t t )
  ( TXT          btxt         btxt             t t t t t )
  ( TXT          ctxt         ctxt             t t t t t )
  ( WN           drawing      wn               t t t t t )
  ( WP           drawing      wp               t t t t t )
  ( DUMBM        drawing      dumbm            t t t t t )
  ( DUMBA        drawing      dumba            t t t t t )
  ( DUMBP        drawing      dumbp            t t t t t )
  ( VARMOS       drawing      varmos           t t t t t )
  ( VARJUN       drawing      varjun           t t t t t )
  ( PFL          drawing      pfl              t t t t t )
  ( SDOP         drawing      sdop             t t t t t )
  ( OPC          opcba        opcba            t t t t t )
  ( OPC          opcbp        opcbp            t t t t t )
  ( OPC          opcbm        opcbm            t t t t t )
  ( NDRF         drawing      ndrf             t t t t t )
  ( PDRF         drawing      pdrf             t t t t t )
  ( PPCI         drawing      ppci             t t t t t )
  ( NPCI         drawing      npci             t t t t t )
  ( PWHT         drawing      pwht             t t t t t )
  ( NWHT         drawing      nwht             t t t t t )
  ( PIP          drawing      pip              t t t t t )
  ( NLHT         drawing      nlht             t t t t t )
  ( PLHT         drawing      plht             t t t t t )
  ( TM1          drawing      tm1              t t t t t )
  ( TM1DUM       drawing      tm1dum           t t t t t )
  ( TM1TXT       drawing      tm1txt           t t t t t )
  ( TV1          drawing      tv1              t t t t t )
  ( TM2          drawing      tm2              t t t t t )
  ( TM2DUM       drawing      tm2dum           t t t t t )
  ( TM2TXT       drawing      tm2txt           t t t t t )
  ( TV2          drawing      tv2              t t t t t )
  ( ESD5V        drawing      esd5v            t t t t t )
  ( LV           drawing      lv               t t t t t )
  ( TG           drawing      tg               t t t t t )
  ( PDC          drawing      pdc              t t t t t )
  ( DCTY         drawing      dcty             t t t t t )
  ( TXT          subtxt       subtxt           t t t t t )
  ( TXT          weltxt       weltxt           t t t t t )
  ( TXT          diftxt       diftxt           t t t t t )
  ( TXT          polytxt      polytxt          t t t t t )
  ( M1B          drawing      m1b              t t t t t )
  ( M2B          drawing      m2b              t t t t t )
  ( M3B          drawing      m3b              t t t t t )
  ( M4B          drawing      m4b              t t t t t )
  ( M5B          drawing      m5b              t t t t t )
  ( M6B          drawing      m6b              t t t t t )
  ( M1DUB        drawing      m1dub            t t t t t )
  ( M2DUB        drawing      m2dub            t t t t t )
  ( M3DUB        drawing      m3dub            t t t t t )
  ( M4DUB        drawing      m4dub            t t t t t )
  ( M5DUB        drawing      m5dub            t t t t t )
  ( M6DUB        drawing      m6dub            t t t t t )
  ( PWH          drawing      pwh              t t t t t )
  ( NWH          drawing      nwh              t t t t t )
  ( M1R          drawing      m1r              t t t t t )
  ( M2R          drawing      m2r              t t t t t )
  ( M3R          drawing      m3r              t t t t t )
  ( M4R          drawing      m4r              t t t t t )
  ( M5R          drawing      m5r              t t t t t )
  ( M6R          drawing      m6r              t t t t t )
  ( MnSLOTB      metal1       m1slotb          t t t t t )
  ( MnSLOTB      metal2       m2slotb          t t t t t )
  ( MnSLOTB      metal3       m3slotb          t t t t t )
  ( MnSLOTB      metal4       m4slotb          t t t t t )
  ( MnSLOTB      metal5       m5slotb          t t t t t )
  ( MnSLOTB      metal6       m6slotb          t t t t t )
  ( NODMF        drawing      nodmf            t t t t t )
  ( RFDEV        drawing      rfdev            t t t t t )
  ( RFMOSD       drawing      rfmosd           t t t t t )
  ( TM1R         drawing      tm1r             t t t t t )
  ( TM2R         drawing      tm2r             t t t t t )
  ( JVARDUM      drawing      jvardum          t t t t t )
  ( HRPDMY       drawing      hrpdmy           t t t t t )
  ( MIMDMY       drawing      mimdmy           t t t t t )
  ( INDMY        drawing      indmy            t t t t t )
  ( STIDMY       drawing      stidmy           t t t t t )
  ( SUBDMY       drawing      subdmy           t t t t t )
  ( DDNW         drawing      ddnw             t t t t t )
  ( LVP          drawing      lvp              t t t t t )
  ( LVN          drawing      lvn              t t t t t )
  ( HVDMY        drawing      hvdmy            t t t t t )
  ( MOSCKT       drawing      mosckt           t t t t t )
  ( DNWTR        drawing      dnwtr            t t t t t )
  ( RESCKT       drawing      resckt           t t t t t )
  ( NFDMK        drawing      nfdmk            t t t t t )
  ( MOMDMY       drawing      momdmy           t t t t t )
  ( MOMDMY       tem          momtem           t t t t t )
  ( RF3T         drawing      rf3t             t t t t t )
  ( MFUSE        drawing      mfuse            t t t t t )
  ( MARKG        drawing      markg            t t t t t )
  ( MARKF        drawing      markf            t t t t t )
  ( MIMCKT       drawing      mimckt           t t t t t )
  ( M1           slot         m1slot           t t t t t )
  ( M2           slot         m2slot           t t t t t )
  ( M3           slot         m3slot           t t t t t )
  ( M4           slot         m4slot           t t t t t )
  ( M5           slot         m5slot           t t t t t )
  ( M6           slot         m6slot           t t t t t )
  ( FUSE         gtfuse       gtfuse           t t t t t )
  ( FUSE         efuse        efuse            t t t t t )
  ( FUSE         mk1          fusemk1          t t t t t )
  ( MARKS        drawing      marks            t t t t t )
  ( DUPMK1       drawing      dupmk1           t t t t t )
  ( INDMY        indr         indr             t t t t t )
  ( INDMY        indor        indor            t t t t t )
  ( MTT1         drawing      mtt1             t t t t t )
  ( MTT2         drawing      mtt2             t t t t t )
  ( RFDN5T       drawing      rfdn5t             t t t t t )
  ( RFDN6T       drawing      rfdn6t             t t t t t )
  ( MIMSHD       drawing      mimshd           t t t t t )
  ( VMK1         luwmk1       luwmk1           t t t t t )
  ( VMK1         vddmk1       vddmk1           t t t t t )
  ( VMK1         vssmk1       vssmk1           t t t t t )
  ( snap         boundary     snap             t t t t nil )
  ( snap         boundary     snap             t t t t nil )
 ) ;techDisplays

 techLayerProperties(
 ;( PropName               Layer1 [ Layer2 ]            PropValue )
 ;( --------               ------ ----------            --------- )
  ( sheetResistance        M1                             0.068000 )
  ( sheetResistance        M2                             0.089860 )
  ( sheetResistance        M3                             0.089860 )
  ( sheetResistance        M4                             0.008300 )
 ) ;techLayerProperties

 techDerivedLayers(
 ;( DerivedLayerName          #          composition  )
 ;( ----------------          ------     ------------ )
  ( noOverlapLayer1           10001           ( GT         'and    AA        ))
  ( nAA                       10004           ( AA         'and    SN        ))
  ( pAA                       10005           ( AA         'and    SP        ))
  ( ntap                      10006           ( nAA        'and    NW        ))
  ( ptap                      10007           ( pAA        'not    NW        ))
  ( ndiff                     10008           ( nAA        'not    NW        ))
  ( pdiff                     10009           ( pAA        'and    NW        ))
 ) ;techDerivedLayers

) ;layerDefinitions


;********************************
; LAYER RULES
;********************************
layerRules(

 functions(
 ;( layer                       function        [maskNumber])
 ;( -----                       --------        ------------)
  ( NW                       	"nwell"     	1            )
  ( GT                       	"poly"      	3            )
  ( AA                       	"diff"      	4            )
  ( SN                       	"nplus"     	5            )
  ( SP                       	"pplus"     	6            )
  ( CT                       	"cut"       	7            )
  ( M1                       	"metal"     	8            )
  ( V1                       	"cut"       	9            )
  ( M2                       	"metal"     	10           )
  ( V2                       	"cut"       	11           )
  ( M3                       	"metal"     	12           )
  ( V3                       	"cut"       	13           )
  ( M4                       	"metal"     	14           )
 ) ;functions

 routingDirections(
 ;( layer                       direction     )
 ;( -----                       ---------     )
  ( GT                       	"none"       )
  ( M1                       	"horizontal" )
  ( M2                       	"vertical"   )
  ( M3                       	"horizontal" )
  ( M4                       	"vertical"   )
 ) ;routingDirections

 stampLabelLayers(
 ;( textLayer   layers        )
 ;( ---------   ----------------------------------        )
  ( M1        	("M1TXT" "drawing")	("M1" "drawing")	 )
  ( M2        	("M2TXT" "drawing")	("M2" "drawing")	 )
  ( M3        	("M3TXT" "drawing")	("M3" "drawing")	 )
  ( M4        	("M4TXT" "drawing")	("M4" "drawing")	 )
 ) ;stampLabelLayers

 currentDensity(
 ;( rule                	layer1    	layer2    	value    )
 ;( ----                	------    	------    	-----    )
  ( avgDCCurrentDensity 	"CT"			0.53	 )
  ( avgDCCurrentDensity 	"M1"			1.0	 )
  ( avgDCCurrentDensity 	"M2"			1.0	 )
  ( avgDCCurrentDensity 	"M3"			1.0	 )
  ( avgDCCurrentDensity 	"M4"			1.6	 )
  ( avgDCCurrentDensity 	"V1"			0.28	 )
  ( avgDCCurrentDensity 	"V2"			0.28	 )
  ( avgDCCurrentDensity 	"V3"			0.706	 )
 ) ;currentDensity

) ;layerRules


;********************************
; VIADEFS
;********************************
viaDefs(

 standardViaDefs(
 ;( viaDefName	layer1	layer2	(cutLayer cutWidth cutHeight [resistancePerCut]) 
 ;   (cutRows	cutCol	(cutSpace)) 
 ;   (layer1Enc) (layer2Enc)	(layer1Offset)	(layer2Offset)	(origOffset) 
 ;   [implant1	 (implant1Enc)	[implant2	(implant2Enc) [well/substrate]]]) 
 ;( -------------------------------------------------------------------------- ) 
  ( M4_M3       	M3          M4          	("V3" 0.36 0.36)
     (1 1 (0.35 0.35))
     (0.06 0.06)	(0.4 0.4)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( M3_M2       	M2          M3          	("V2" 0.26 0.26)
     (1 1 (0.26 0.26))
     (0.06 0.06)	(0.06 0.06)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( M2_M1       	M1          M2          	("V1" 0.26 0.26)
     (1 1 (0.26 0.26))
     (0.06 0.06)	(0.06 0.06)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( M1_SUB      	AA          M1          	("CT" 0.22 0.22)
     (1 1 (0.25 0.25))
     (0.1 0.1)	(0.06 0.06)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
     SP          	(0.18 0.18)
  )
  ( M1_SP       	AA          M1          	("CT" 0.22 0.22)
     (1 1 (0.25 0.25))
     (0.1 0.1)	(0.06 0.06)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
     SP          	(0.18 0.18)
  )
  ( M1_NW       	AA          M1          	("CT" 0.22 0.22)
     (1 1 (0.25 0.25))
     (0.1 0.1)	(0.06 0.06)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
     SN          	(0.18 0.18)	NW          	(0.22 0.22)	NW             
  )
  ( M1_SN       	AA          M1          	("CT" 0.22 0.22)
     (1 1 (0.25 0.25))
     (0.1 0.1)	(0.06 0.06)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
     SN          	(0.18 0.18)
  )
  ( M1_AA       	AA          M1          	("CT" 0.22 0.22)
     (1 1 (0.25 0.25))
     (0.1 0.1)	(0.06 0.06)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( M1_GT       	GT          M1          	("CT" 0.22 0.22)
     (1 1 (0.25 0.25))
     (0.1 0.1)	(0.06 0.06)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
 ) ;standardViaDefs

) ;viaDefs



;********************************
; CONSTRAINT GROUPS
;********************************
constraintGroups(

 ;( group	[override] )
 ;( -----	---------- )
  ( "virtuosoDefaultExtractorSetup"	nil

    interconnect(
     ( validLayers   (M4  V3  M3  V2  M2  V1  M1  CT  GT  SP  SN  AA  NW  ) )
     ( validVias     (M4_M3  M3_M2  M2_M1  M1_GT  M1_AA  M1_NW  M1_SN  M1_SP  M1_SUB  ) )
     ( errorLayer    noOverlapLayer1 )
    ) ;interconnect
  ) ;virtuosoDefaultExtractorSetup

 ;( group	[override] )
 ;( -----	---------- )
  ( "virtuosoDefaultTaper"	nil    "taper"

    interconnect(
     ( validLayers   (GT  M1  ) )
     ( validVias     (M1_GT  ) )
    ) ;interconnect

    spacings(
     ( taperHalo                  0.0 )
    ) ;spacings
  ) ;virtuosoDefaultTaper

 ;( group	[override] )
 ;( -----	---------- )
  ( "VLMDefaultSetup"	nil

    interconnect(
     ( validLayers   (M4  V3  M3  V2  M2  V1  M1  CT  GT  SP  SN  AA  NW  ) )
     ( validVias     (M4_M3  M3_M2  M2_M1  M1_GT  M1_AA  M1_NW  M1_SN  M1_SP  M1_SUB  ) )
    ) ;interconnect
  ) ;VLMDefaultSetup

 ;( group	[override] )
 ;( -----	---------- )
  ( "virtuosoDefaultSetup"	nil

    interconnect(
     ( validLayers   (M4  V3  M3  V2  M2  V1  M1  CT  GT  SP  SN  AA  NW  ) )
     ( validVias     (M4_M3  M3_M2  M2_M1  M1_GT  M1_AA  M1_NW  M1_SN  M1_SP  M1_SUB  ) )
    ) ;interconnect
  ) ;virtuosoDefaultSetup

 ;( group	[override] )
 ;( -----	---------- )
  ( "LEFDefaultRouteSpec"	nil    "LEFDefaultRouteSpec"

    interconnect(
     ( validLayers   (M4  V3  M3  V2  M2  V1  M1  ) )
     ( validVias     (M4_M3  M3_M2  M2_M1  ) )
    ) ;interconnect

    spacings(
     ( minWidth                   "CT"	0.22 )
     ( viaSpacing                 "CT"  (3 0.28 0.25)  'ref  "rule CT.3" )
    ) ;spacings

    routingGrids(
     ( horizontalPitch            "M1"   0.46 )
     ( verticalPitch              "M1"   0.46 )
     ( horizontalOffset           "M1"   0.0 )
     ( verticalOffset             "M1"   0.0 )
    ) ;routingGrids

    spacings(
     ( minWidth                   "M1"	0.23 )
     ( minWidth                   "V1"	0.26 )
    ) ;spacings

    routingGrids(
     ( horizontalPitch            "M2"   0.56 )
     ( verticalPitch              "M2"   0.56 )
     ( horizontalOffset           "M2"   0.0 )
     ( verticalOffset             "M2"   0.0 )
    ) ;routingGrids

    spacings(
     ( minWidth                   "M2"	0.28 )
     ( minWidth                   "V2"	0.26 )
    ) ;spacings

    routingGrids(
     ( horizontalPitch            "M3"   0.56 )
     ( verticalPitch              "M3"   0.56 )
     ( horizontalOffset           "M3"   0.0 )
     ( verticalOffset             "M3"   0.0 )
    ) ;routingGrids

    spacings(
     ( minWidth                   "M3"	0.28 )
     ( minWidth                   "V3"	0.36 )
    ) ;spacings

    routingGrids(
     ( horizontalPitch            "M4"   5.1 )
     ( verticalPitch              "M4"   5.1 )
     ( horizontalOffset           "M4"   0.0 )
     ( verticalOffset             "M4"   0.0 )
    ) ;routingGrids

    spacings(
     ( minWidth                   "M4"	2.6 )
    ) ;spacings
  ) ;LEFDefaultRouteSpec

 ;( group	[override] )
 ;( -----	---------- )
  ( "foundry"	nil

    interconnect(
     ( validLayers   (M4  V3  M3  V2  M2  V1  M1  CT  GT  SP  SN  AA  NW  ) )
     ( validVias     (M4_M3  M3_M2  M2_M1  M1_GT  M1_AA  M1_NW  M1_SN  M1_SP  M1_SUB  ) )
    ) ;interconnect

    spacings(
     ( minWidth                   "DNW"	3.0 )
     ( minWidth                   "NW"	0.86 )
     ( minWidth                   "PSUB"	0.84 )
     ( minWidth                   "MVN"	0.72 )
     ( minWidth                   "MVP"	0.72 )
     ( minWidth                   "AA"	0.22 )
     ( minWidth                   "DG"	0.86 )
     ( minWidth                   "GT"	0.18 )
     ( minWidth                   "NLL"	0.44 )
     ( minWidth                   "PLL"	0.44 )
     ( minWidth                   "NLH"	0.44 )
     ( minWidth                   "PLH"	0.44 )
     ( minWidth                   "SN"	0.44 )
     ( minWidth                   "SP"	0.44 )
     ( minWidth                   "SAB"	0.43 )
     ( minWidth                   "CT"	0.22 )
     ( minWidth                   "M1"	0.23 )
     ( minWidth                   "V1"	0.26 )
     ( minWidth                   "M2"	0.28 )
     ( minWidth                   "V2"	0.26 )
     ( minWidth                   "M3"	0.28 )
     ( minWidth                   "V3"	0.36 )
     ( minWidth                   "M4"	2.6 )
     ( minWidth                   "MIM"	4.0 )
     ( minWidth                   "HRP"	0.44 )
     ( minSpacing                 "DNW"	5.0 )
     ( minSpacing                 "NW"	1.4 )
     ( minSpacing                 "PSUB"	0.84 )
     ( minSpacing                 "MVN"	0.42 )
     ( minSpacing                 "MVP"	0.42 )
     ( minSpacing                 "AA"	0.28 )
     ( minSpacing                 "DG"	0.45 )
     ( minSpacing                 "GT"	0.25 )
     ( minSpacing                 "NLL"	0.44 )
     ( minSpacing                 "PLL"	0.44 )
     ( minSpacing                 "NLH"	0.44 )
     ( minSpacing                 "PLH"	0.44 )
     ( minSpacing                 "SN"	0.44 )
     ( minSpacing                 "SP"	0.44 )
     ( minSpacing                 "SAB"	0.43 )
     ( minSpacing                 "CT"	0.25 )
     ( minSpacing                 "M1"	0.23 )
     ( minSpacing                 "V1"	0.26 )
     ( minSpacing                 "M2"	0.28 )
     ( minSpacing                 "V2"	0.26 )
     ( minSpacing                 "M3"	0.28 )
     ( minSpacing                 "V3"	0.35 )
     ( minSpacing                 "M4"	2.5 )
     ( minSpacing                 "MIM"	1.2 )
     ( minSpacing                 "HRP"	0.44 )
     ( minArea                    "AA"	0.2 )
     ( minArea                    "NLL"	0.4 )
     ( minArea                    "PLL"	0.4 )
     ( minArea                    "NLH"	0.4 )
     ( minArea                    "PLH"	0.4 )
     ( minArea                    "SN"	0.38 )
     ( minArea                    "SP"	0.38 )
     ( minArea                    "SAB"	2.0 )
     ( minArea                    "M1"	0.2 )
     ( minArea                    "M2"	0.2 )
     ( minArea                    "M3"	0.2 )
     ( minArea                    "M4"	6.76 )
     ( maxWidth                   "CT"	0.22 )
     ( maxWidth                   "M1"	35.0 )
     ( maxWidth                   "V1"	0.26 )
     ( maxWidth                   "M2"	35.0 )
     ( maxWidth                   "V2"	0.26 )
     ( maxWidth                   "M3"	35.0 )
     ( maxWidth                   "V3"	0.36 )
     ( maxWidth                   "M4"	35.0 )
     ( minDensity                 "GT"	0.14 )
     ( minDensity                 "M1"	0.3 )
     ( maxDensity                 "M1"	0.75 )
     ( minDensity                 "M2"	0.3 )
     ( maxDensity                 "M2"	0.75 )
     ( minDensity                 "M3"	0.3 )
     ( maxDensity                 "M3"	0.75 )
     ( minDensity                 "M4"	0.3 )
     ( maxDensity                 "M4"	0.75 )
     ( minLargeViaArrayCutSpacing "CT"	0.28  'ref  "CT.3" )
     ( minLargeViaArrayWidth      "CT"	1.15 )
    ) ;spacings

    orderedSpacings(
     ( minExtensionDistance       "AA"	"CT"		0.1 )
     ( minExtensionDistance       "GT"	"CT"		0.1 )
     ( minExtensionDistance       "M1"	"CT"		0.005 )
     ( minExtensionDistance       "M1"	"V1"		0.01 )
     ( minExtensionDistance       "M2"	"V1"		0.01 )
     ( minExtensionDistance       "M2"	"V2"		0.01 )
     ( minExtensionDistance       "M3"	"V2"		0.01 )
     ( minExtensionDistance       "M3"	"V3"		0.01 )
     ( minExtensionDistance       "M4"	"V3"		0.4 )
     ( minOppExtension            "AA"	"CT"		(0.1 0.1)  'ref  "CT.6" )
     ( minOppExtension            "GT"	"CT"		(0.1 0.1)  'ref  "CT.7" )
     ( minOppExtension            "M1"	"CT"		(0.06 0.005)  'ref  "M1.4 M1.3" )
     ( minOppExtension            "M1"	"V1"		(0.06 0.01)  'ref  "V1.4 V1.3" )
     ( minOppExtension            "M2"	"V1"		(0.06 0.01)  'ref  "Vn.4 Vn.3" )
     ( minOppExtension            "M2"	"V2"		(0.06 0.01)  'ref  "Vn.4 Vn.3" )
     ( minOppExtension            "M3"	"V2"		(0.06 0.01)  'ref  "Vn.4 Vn.3" )
     ( minOppExtension            "M3"	"V3"		(0.06 0.01)  'ref  "V5.4 V5.3" )
     ( minOppExtension            "M4"	"V3"		(0.45 0.4)  'ref  "MTT2.4 MTT2.3" )
     ( minExtensionDistance       "NW"	"DNW"		1.5  'ref  "DNW.4" )
     ( minExtensionDistance       "NW"	"nAA"		0.12  'ref  "AA.4" )
     ( minExtensionDistance       "NW"	"pAA"		0.43  'ref  "AA.6" )
     ( minExtensionDistance       "DG"	"AA"		0.32  'ref  "DG.1" )
     ( minExtensionDistance       "SAB"	"AA"		0.22  'ref  "SAB.6" )
    ) ;orderedSpacings

    antennaModels(
    ;( model )
    ;( ----- )
     ( "default"
       antenna(
	( areaRatio          "GT"     200.0 )
       ) ;antenna
       antenna(
	( areaRatio          "CT"     10.0 )
       ) ;antenna
       antenna(
	( areaRatio          "M1"     400.0 )
       ) ;antenna
       antenna(
	( areaRatio          "V1"     20.0 )
       ) ;antenna
       antenna(
	( areaRatio          "M2"     400.0 )
       ) ;antenna
       antenna(
	( areaRatio          "V2"     20.0 )
       ) ;antenna
       antenna(
	( areaRatio          "M3"     400.0 )
       ) ;antenna
       antenna(
	( areaRatio          "V3"     20.0 )
       ) ;antenna
       antenna(
	( areaRatio          "M4"     400.0 )
       ) ;antenna
     ) ;default
    ) ;antennaModels
  ) ;foundry
) ;constraintGroups


;********************************
; DEVICES
;********************************
devices(
tcCreateCDSDeviceClass()





multipartPathTemplates(
; ( name [masterPath] [offsetSubpaths] [encSubPaths] [subRects] )
; 
;   masterPath:
;   (layer [width] [choppable] [endType] [beginExt] [endExt] [justify] [offset]
;   [connectivity])
; 
;   offsetSubpaths:
;   (layer [width] [choppable] [separation] [justification] [begOffset] [endOffset]
;   [connectivity])
; 
;   encSubPaths:
;   (layer [enclosure] [choppable] [separation] [begOffset] [endOffset]
;   [connectivity])
; 
;   subRects:
;   (layer [width] [length] [choppable] [separation] [justification] [space] [begOffset] [endOffset] [gap] 
;   [connectivity] [beginSegOffset] [endSegOffset])
; 
;   connectivity:
;   ([I/O type] [pin] [accDir] [dispPinName] [height] [ layer]
;    [layer] [justification] [font] [textOptions] [orientation]
;    [refHandle] [offset])
; 
; ( --------------------------------------------------------------------- )
  (NGR 
    (("AA" "drawing")	(0.22 + (2 * 0.1))	t)
    ((("M1" "drawing")	(0.22 + (2 * 0.06))	t	0         	center	(- (0.1 - 0.06))	
     (minus	(0.1 - 0.06)	))
     (("NW" "drawing")	0.86	t	0         	center	0.22	0.22)
    )
    ((("SN" "drawing")	-0.18	t)
    )
    ((("CT" "drawing")	0.22	0.22	t	0         	center	0.25	(-0.25 / 2)	(-0.25 / 2)	distribute)
    )
  )
  (PGR 
    (("AA" "drawing")	(0.22 + (2 * 0.1))	t)
    ((("M1" "drawing")	(0.22 + (2 * 0.06))	t	0         	center	(- (0.1 - 0.06))	
     (minus	(0.1 - 0.06)	))
    )
    ((("SP" "drawing")	-0.02	t)
    )
    ((("CT" "drawing")	0.22	0.22	t	0         	center	0.25	(-0.25 / 2)	(-0.25 / 2)	distribute)
    )
  )
)  ;multipartPathTemplates




) ;devices


;********************************
; VIASPECS
;********************************

viaSpecs(
 ;(layer1  layer2  (viaDefName ...) 
 ;   [(        
 ;	(layer1MinWidth layer1MaxWidth layer2MinWidth layer2MaxWidth 
 ;            (viaDefName ...)) 
 ;	...         
 ;   )])       
 ;( ------------------------------------------------------------------------ ) 
   ( M3      M4      ("M4_M3")
   )
   ( M2      M3      ("M3_M2")
   )
   ( M1      M2      ("M2_M1")
   )
   ( GT      M1      ("M1_GT")
   )
) ;viaSpecs
